/**
    This code is autogenerated using Capriccio 1.1.0 - https://github.com/shibapm/capriccio
    Implement the missing code in a extension, i.e.

    ```
    extension XCTestCase {
        func step<step name>() {}
    }
    ```

    DO NOT EDIT
*/
import XCTest

/**
Feature:
    View score on Dashboard
*/

class ViewScoreOnDashboardFeatureTest: XCTestCase {
    override func setUp() {
        super.setUp()
        
        continueAfterFailure = false
    }
    
    override func tearDown() {
        super.tearDown()
    }
      
    func testScenario_UserCanSeeTheScore_CanAndHas() {
        launchScenarioUserCanSeeTheScore(with: "CanAndHas")
        stepUserIsOnTheDashboardScreen()
        stepUserNetwork(hasOrNot: "has")
        stepUserSeeTheScore(canOrNot: "can")
    } 
    func testScenario_UserCanSeeTheScore_CannotAndHasNot() {
        launchScenarioUserCanSeeTheScore(with: "CannotAndHasNot")
        stepUserIsOnTheDashboardScreen()
        stepUserNetwork(hasOrNot: "has not")
        stepUserSeeTheScore(canOrNot: "cannot")
    }   
}
